name: the_business_square
description: A new Flutter project.

publish_to: "none"

version: 1.1.7

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:
  get:
  easy_image_viewer:
  get_storage:
  flutter_bloc:
  connectivity_plus: ^2.3.6
  dartz:
  dio:

  flutter_svg:
  animated_bottom_navigation_bar:

  image_picker: ^0.8.5+3
  flutter_switch: ^0.3.2
  stylish_bottom_bar: ^0.1.5
  url_launcher:
  # Functional programming things
  equatable: ^2.0.3
  flutter_emoji:
  get_it: ^7.2.0
  json_annotation: ^4.7.0
  loading_animations: ^2.2.0
  json_serializable: ^6.5.4
  # Dependency Injection
  injectable: ^2.1.0
  fluttertoast:
  loading_indicator: ^3.1.0
  file_picker:
  linkwell: ^2.0.6
  shimmer:
  photo_view: ^0.14.0
  webview_flutter: ^3.0.4

  flutter_local_notifications: "12.0.4"
  firebase_core: ^2.1.1
  firebase_messaging:
  share_plus: ^6.3.1
  permission_handler:

  agora_uikit: ^1.3.10
  uuid:
  my_fatoorah: ^3.3.0

  pusher_channels_flutter: ^2.2.0
  crypto: 3.0.3
  cached_network_image: ^3.3.0
  dashed_rect:
  timeago:
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed:
  injectable_generator: ^2.1.3
  build_runner:
  flutter_lints: ^2.0.0
  freezed_annotation:
  watcher:  ^1.1.0
  flutter_launcher_icons:

  #flutter pub run flutter_launcher_icons:main

  flutter_native_splash:
  #flutter pub run flutter_native_splash:create

  change_app_package_name:
  #flutter pub run change_app_package_name:main com.new.package.name

flutter_icons:
  android: true
  ios: true
  image_path: "assets/launcher/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/launcher/icon.png"

flutter_native_splash:
  background_image: "assets/launcher/icon.png"
  fullscreen: true
  android: true
  ios: true
  web: true

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/
    - assets/launcher/
    - assets/fonts/
    - assets/image/

  fonts:
    - family: font
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700






